[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable secrets scanning for Stripe publishable key
  # (pk_test_ keys are meant to be public)
  SECRETS_SCAN_OMIT_KEYS = "VITE_STRIPE_PUBLISHABLE_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

